### ISSUE TITLE
Unable to run Lambda.agda

### ISSUE THREAD

**Issue by arey0pushpa** [UlfNorell/agda-summer-school#3] opened 2016-05-02 05:23 UTC
I'm following your OPLSS 2015 lectures and have setup things like it should according to the https://github.com/UlfNorell/agda-summer-school.

Agda2 Include Dirs:
INS DEL Directory: .
INS DEL Directory: /home/mokambo/src/agda/lib/src
INS DEL Directory: /home/mokambo/agda-prelude/src
INS

Error while type checking showing :

/media/mokambo/Pablo Naruda/ORAGON/AGDA/agda-summer-school/lectures/Lambda.agda:8,6-6
/media/mokambo/Pablo Naruda/ORAGON/AGDA/agda-summer-school/lectures/Lambda.agda:8,6: Parse error
import < ERROR >
Term.Show
open import Lists

...

Why it should it giving parse error or import error?

I'm using Agda version 2.4.0.2.

**Comment by UlfNorell** [comment] 2016-05-02 06:56
I can't reproduce that particular error, but the OPLSS branch is not compatible with `agda-2.4.0.2`. Another problem might be the `.../agda/lib/src` include. The `2.4.*` versions of `agda-prelude` are incompatible with the standard library.

 I've created new branches for different agda versions:
- `OPLSS-2.4.0.2`
- `OPLSS-2.4.2.5`
- `OPLSS-2.5.1`

You can try and see if the `2.4.0.2` branch works, but my suggestion is that you upgrade to `2.5.1`. `2.4.0.2` is two years old by now.

I'm closing the issue, but feel free to reopen it if the problem persists.

**Closed as completed by UlfNorell** 2016-05-02 06:56 UTC

**Comment by arey0pushpa** [comment] 2016-05-02 16:31
When ever i'm doing import its giving me an error. 
module RedBlack where

open import Data.Nat

Any use without import works fine. So that looks library compatibility !? What should i do ? I have installed agda 2.5.1 but don't know how to manage version. ?

**Comment by arey0pushpa** [comment] 2016-05-03 13:49
Yeah problem is of compatibility. How to version manage agda ?? Means how to tell for example : cabal use Agda-2.5.1 ?? Thanks .
